<main class="main-container">
    <section class="top-bar ">
        <div>
            <div>
            <a href="?page=dashboard"><img src="../public/assets/img/icons/icon-arrow-left.svg"/>Retour</a> 

            </div>

            <input type="search" class="searchbar" placeholder="Rechercher un film, un personnage..."/>
        </div>  
        <div>
            <a href="?page=login" class="profile">
                <p>Se connecter</p>
                <img src="../public/assets/img/profile.png"/>
            </a>
            <div class="logout">
                <img src="../public/assets/img/icons/icon-logout.svg"/>
            </div>
        </div>

    </section>

    <div class="title-container container">
        <h1>Oups Erreur 404,</h1>
        <p>Il n'y a rien ici, demi tour soldat !</p>
        <a href="?page=dashboard">Retour au tableau de bord</a>
    </div>
    


</main>
